# Generated by Django 5.2.1 on 2025-06-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gugun', models.CharField(max_length=30)),
                ('perform_inst', models.CharField(max_length=100)),
                ('bsns_nm', models.CharField(max_length=100)),
                ('bsns_kind', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('people', models.IntegerField()),
                ('bsns_main_activ', models.TextField()),
                ('bsns_sdate', models.DateField()),
                ('bsns_fdate', models.DateField()),
                ('data_day', models.DateField()),
                ('record_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='seniorjob.seniorjob')),
            ],
        ),
    ]
