# Generated by Django 4.2.21 on 2025-06-22 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('number', '숫자'), ('word', '단어'), ('memory', '기억'), ('time', '시간'), ('general', '일반상식'), ('season', '계절/이벤트')], default='general', max_length=20)),
                ('question', models.TextField(verbose_name='문제')),
                ('answer', models.TextField(verbose_name='정답')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='힌트')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_attempts', models.IntegerField(default=0, verbose_name='총 시도 횟수')),
                ('correct_attempts', models.IntegerField(default=0, verbose_name='정답 횟수')),
            ],
            options={
                'verbose_name': '퀴즈',
                'verbose_name_plural': '퀴즈 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quizzes', models.ManyToManyField(to='quiz.quiz', verbose_name='선택된 퀴즈들')),
            ],
            options={
                'verbose_name': '일일 퀴즈 세트',
                'verbose_name_plural': '일일 퀴즈 세트 목록',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='사용자 답변')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('attempt_date', models.DateField(auto_now_add=True, verbose_name='시도 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈 결과',
                'verbose_name_plural': '퀴즈 결과 목록',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quiz', 'attempt_date')},
            },
        ),
    ]
