# Generated by Django 4.2.21 on 2025-06-11 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSupport',
            fields=[
                ('support_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('apply_url', models.TextField()),
                ('support_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_support',
            },
        ),
        migrations.CreateModel(
            name='CultureSupportDetail',
            fields=[
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='support.publicsupport')),
                ('category', models.CharField(max_length=50)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'culture_support_detail',
            },
        ),
        migrations.CreateModel(
            name='WelfareSupportDetail',
            fields=[
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='support.publicsupport')),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'welfare_support_detail',
            },
        ),
        migrations.CreateModel(
            name='UserSupportMatch',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.publicsupport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_support_match',
            },
        ),
        migrations.CreateModel(
            name='CounselRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('emergency', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counsel_request',
            },
        ),
    ]
