# Generated by Django 4.2.21 on 2025-06-17 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('tel', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bus_stop', models.CharField(default='정보 없음', max_length=20)),
                ('holiday_open', models.BooleanField(default=False)),
                ('is_partnered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('service_used', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical.medicalfacility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
