# Generated by Django 5.2.1 on 2025-06-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('tel', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bus_stop', models.CharField(default='정보 없음', max_length=20)),
                ('holiday_open', models.BooleanField(default=False)),
                ('is_partnered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('service_used', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_visits', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='medical.medicalfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='약 이름')),
                ('type', models.CharField(choices=[('TAB', '정제'), ('CAP', '캡슐'), ('SYR', '시럽'), ('INJ', '주사제'), ('POW', '가루약'), ('GEL', '겔제'), ('OTR', '기타')], max_length=3, verbose_name='약 종류')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='입력일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pill_images/', verbose_name='약봉투 사진')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
