# Generated by Django 4.2.7 on 2025-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='bus_stop',
            field=models.CharField(default='정보 없음', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='holiday_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='tel',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
