# Generated by Django 4.2.21 on 2025-06-17 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='약 이름')),
                ('type', models.CharField(choices=[('TAB', '정제'), ('CAP', '캡슐'), ('SYR', '시럽'), ('INJ', '주사제'), ('POW', '가루약'), ('GEL', '겔제'), ('OTR', '기타')], max_length=3, verbose_name='약 종류')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='입력일')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pill_images/', verbose_name='약봉투 사진')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
