# Generated by Django 4.2.21 on 2025-06-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0002_pill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pill',
            options={'ordering': ['-date_added'], 'verbose_name': '약', 'verbose_name_plural': '약 목록'},
        ),
        migrations.AddField(
            model_name='pill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='pill',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='용량'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pills/', verbose_name='약봉투 이미지'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='type',
            field=models.CharField(choices=[('TAB', '정제'), ('CAP', '캡슐'), ('SYR', '시럽'), ('INJ', '주사제'), ('POW', '가루약'), ('GEL', '겔제')], default='TAB', max_length=3, verbose_name='약 종류'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pills', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
