# Generated by Django 4.2.21 on 2025-06-18 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0003_alter_pill_options_pill_description_pill_dosage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pill',
            options={},
        ),
        migrations.RemoveField(
            model_name='pill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='dosage',
        ),
        migrations.AlterField(
            model_name='pill',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='입력일'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pill_images/', verbose_name='약봉투 사진'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='type',
            field=models.CharField(choices=[('TAB', '정제'), ('CAP', '캡슐'), ('SYR', '시럽'), ('INJ', '주사제'), ('POW', '가루약'), ('GEL', '겔제'), ('OTR', '기타')], max_length=3, verbose_name='약 종류'),
        ),
        migrations.AlterField(
            model_name='pill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pills', to=settings.AUTH_USER_MODEL),
        ),
    ]
