# Generated by Django 4.2.21 on 2025-06-11 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMealCard',
            fields=[
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('child_id', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('subsidy_limit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'child_meal_card',
            },
        ),
        migrations.CreateModel(
            name='MealStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('merchant_type', models.CharField(max_length=50)),
                ('is_free_meal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'meal_store',
            },
        ),
        migrations.CreateModel(
            name='MealTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('amount', models.IntegerField()),
                ('item_category', models.CharField(max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='meal_card.childmealcard')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_card.mealstore')),
            ],
            options={
                'db_table': 'meal_transaction',
            },
        ),
    ]
